server:
  servlet:
    context-path: kafka
  port: 8001
  #springboot整合kafka
spring:
  kafka:
    producer:
      # zookeeper集群地址
      bootstrap-servers: 192.168.120.131:9092
      # 发送失败后重试次数
      retries: 0
      # 批量发送默认大小，当满足这个大小就会批量发送
      batch-size: 16384
      # 设置kafka生产者内存缓存区的大小（32M）
      buffer-memory: 33554432
      # kafka消息序列化配置
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # acks=0 ：生产者在成功写入消息前，不会等待任何来自服务器的响应。
      # acks=1 ：只要集群的首领节点收到消息，生产者就会收到一个来自服务器成功响应。
      # acks=-1或all ：表示分区leader必须等待消息被成功写入到所有的ISR副本（同步副本）中才认为producer请求成功
      # 这种方案理提供最高的消息持久性保证，但是理论上吞吐率也是最差的。
      # 这个是kafka生产者最重要的配置
      acks: 1